### PR TITLE
Added nuget package creation

### PR DESCRIPTION
**Pull request by philchuang**
Consolidated up .net framework versions and nuget packages, and added scripts to create a nuget package

### CODE REVIEW

**Comment by barrywimlett** [comment]
[EliteJournalReader.csproj.txt](https://github.com/MagicMau/EliteJournalReader/files/5757644/EliteJournalReader.csproj.txt)

If you are going to do this please consider moving projects to SDK format and then supporting ALL possible framework versions

See attached

**Comment by MagicMau** [comment]
Hi @philchuang, thanks for the pull request. Very much appreciated! Could you incorporate @barrywimlett's suggestion?

**Comment by barrywimlett** [comment]
Added my own pull-request for changes as requested :D 

https://github.com/MagicMau/EliteJournalReader/pull/13

**Comment by MagicMau** [comment]
This pull request has been superseded by #13 and that one has been merged into master now.

**Pull request closed without merging**
